name: Node.js CI  
on: #Evento
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs: #Tareas
 build-and-test:
  runs-on: ubuntu-latest # Runner
  steps:
    - name: Clonar repositorio #1
      uses: actions/checkout@v3
    - name: Usar Node.js # 2
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Instalar dependencias # 3
      run: npm install
    - name: Ejecutar pruebas # 4
      run: npm test
    - name: Ver entorno #5
      run: echo "Entorno actual ${{ secrets.NODE_ENV }}"
